name: Validate

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23
      - run: nix run .#nix-develop .#workflow
      - run: pnpm install

      - run: ./node_modules/.bin/tsc --build
      - run: pnpm run build
