name: Validate

on: push

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - run: npm install

      - run: ./node_modules/.bin/tsc --build
      - run: npm run build
